// Teste das Restrições REST dos prestadores

@baseURL = http://localhost:4000/api/prestadores

// GET - Lista dods os prestadores
GET {{baseURL}}
Content-Type: application/json

###
// GET - Lista de regisro pela id
GET {{baseURL}}/id/65085a15bcc1245ffa4101d4
Content-Type: application/json

###
// DELETE - Apaga um registro pela id
DELETE {{baseURL}}/65085a15bcc1245ffa4101d4
Content-Type: application/json

###
// POST - Insere um novo registro
POST {{baseURL}}
Content-Type: application/json

{
    "cnpj": "45150718000149",
    "razao_social": "DERROTA ALACARTE ME",
    "cnae_fiscal": 451510,
    "nome_fantasia": "DERROTA MEN",
    "data_inicio_atividade": "2020-08-01",
    "localizacao": {
        "type": "Point",
        "coordinates": [-23.2904, -47.2963]
    }
}
